### ISSUE TITLE
dune habitat with no vegetation

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-mhq-data#37]
pq 10578737_2120 (2018-09-27), 10342193_2120 (2019-10-15) and 3807153_2120 (2020-08-24) -> 100% sand in the 3 x 3 plot. The first two pq are partially covered by herb layer in the circle plot. Should we use the species cover in the circle plot in these cases.

pq 601649 (2021-08-17) --> vegetation data is missing (4 types of struweelsoorten are present in the circle plot, but nog species are listed)

**Comment by Patrikoosterlynck** [comment]
pq 601649: i suggest deleting this incomplete record

For the 3 plots with no vegetation layer in the 3x3 some considerations first:
1. LSVI calculation of 2120 is complex due to different successional stage (open sand to Ammophila vegetation)
2. Scale of the indicators is important (3X3 vs circle)
3. LSVI indicators were not calculated in previous reporting 
4. There is only a limited set of vegetation data for the circle plot level 

I propose a evaluation hierarchy in appendix
In case there is no vegetation in the 3x3 I propose not calculating sleutelsoorten en horinzontale structuur, since dunes without vegetation can have a favourable CS (only rijshout, structuurverstoring (en naakte bodem via mapping) need to be checked)


 
[eval_LSVI_2120.xlsx](https://github.com/user-attachments/files/16157478/eval_LSVI_2120.xlsx)

**Comment by ToonHub** [comment]
OK. I agree.
